# Generated by Django 4.0.1 on 2022-01-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_orderplaced_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
    ]
